### ISSUE TITLE
No adapters file available 

### ISSUE THREAD

**Issue by AndreaAguadoM** [dezordi/IAM_SARSCOV2#10]
Helllo 

My name is Andrea, and I am currently working with a set of SARS-CoV-2 sequences obtained by Illumina tech in order to find different SNVs that lead to the identification of viral quasispecies. My problem resides on the fact that i do not posess the adapters file required in the workflow of ViralFlow, so I was wondering if there is a possibility of running the code without the adapters file. 

Thanks in advance

**Comment by dezordi** [comment]
> Helllo
> 
> My name is Andrea, and I am currently working with a set of SARS-CoV-2 sequences obtained by Illumina tech in order to find different SNVs that lead to the identification of viral quasispecies. My problem resides on the fact that i do not posess the adapters file required in the workflow of ViralFlow, so I was wondering if there is a possibility of running the code without the adapters file.
> 
> Thanks in advance

Hello Andrea, the data that you are working on are generated throughout an amplicon sequencing approach?

**Comment by AndreaAguadoM** [comment]
> > Helllo
> > My name is Andrea, and I am currently working with a set of SARS-CoV-2 sequences obtained by Illumina tech in order to find different SNVs that lead to the identification of viral quasispecies. My problem resides on the fact that i do not posess the adapters file required in the workflow of ViralFlow, so I was wondering if there is a possibility of running the code without the adapters file.
> > Thanks in advance
> 
> Hello Andrea, the data that you are working on are generated throughout an amplicon sequencing approach?

Yes, they are

**Comment by dezordi** [comment]
> > > Helllo
> > > My name is Andrea, and I am currently working with a set of SARS-CoV-2 sequences obtained by Illumina tech in order to find different SNVs that lead to the identification of viral quasispecies. My problem resides on the fact that i do not posess the adapters file required in the workflow of ViralFlow, so I was wondering if there is a possibility of running the code without the adapters file.
> > > Thanks in advance
> > 
> > 
> > Hello Andrea, the data that you are working on are generated throughout an amplicon sequencing approach?
> 
> Yes, they are

So you should parse an adapter file with the primers used in the PCR analysis, if you don't pass it, probably some mutations will be considered as intrahost sites, in an analysis of quasispecies, you will have "artificial quasispecies", because the primer sequences will force a reference base in positions with SNPs on primer binding site.

But, if you want to run without primers remotion, you can pass an empty file (e.g. the ART_adapters.fa present on the test_files directory) as an adapter file, this is not the most elegant way, but as viralflow requires a primer file (because the workflow was developed do amplicon sequencing datasets) you should pass one.

We are working on a new version of viraflow, a more "flexible" version, that the adapters file will be optional, I'll maintain this issue open until we develop that.

Best,
